export const LOAD_PRODUCTS_START ="LOAD_PRODUCTS_START"
export const LOAD_PRODUCTS_SUCCESS ="LOAD_PRODUCTS_SUCCESS"
export const LOAD_PRODUCTS_ERROR ="LOAD_PRODUCTS_ERROR"

export const CREATE_PRODUCT_START="CREATE_PRODUCT_START"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILURE="CREATE_PRODUCT_FAILURE"

export const ADD_TO_CART_START = "ADD_TO_CART_START"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const LOAD_CART_START ="LOAD_CART_START"
export const LOAD_CART_SUCCESS ="LOAD_CART_SUCCESS"
export const LOAD_CART_ERROR ="LOAD_CART_ERROR"

export const REMOVE_FROM_CART_START = "REMOVE_FROM_CART_START"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE"

export const SEARCH_PRODUCT="SEARCH_PRODUCT"
// export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"

export const CREATE_USER_START="CREATE_USER_START"
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE="CREATE_USER_FAILURE"

export const REMOVE_FROM_PRODUCTS_START = "REMOVE_FROM_PRODUCTS_START"
export const REMOVE_FROM_PRODUCTS_SUCCESS = "REMOVE_FROM_PRODUCTS_SUCCESS"
export const REMOVE_FROM_PRODUCTS_FAILURE = "REMOVE_FROM_PRODUCTS_FAILURE"